import Head from 'next/head';
import Link from 'next/link';
import { useAppSelector } from '@/store/hooks';
import { selectIsUserLogged } from '@/store/slices/auth/authSlice';
import ui from '@/styles/interface/ui.module.sass';
import BackgroundVideo from '@/components/BackgroundVideo';

export default function Home() {
    const isUserLogged = useAppSelector(selectIsUserLogged);
    const style = isUserLogged ? 'page' : 'page page-fullscreen';
    console.log(style);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={style}>
                <div className="page-content">
                    <BackgroundVideo />
                    <Link className={ui.button} href="/auth/login">
                        Login
                    </Link>
                </div>
            </main>
        </>
    );
}
